[package]
name = "bevy_sample_app"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", features = ["dynamic_linking"]}
once_cell = "1.21.3"
rand = "0.8"
rand_chacha = "0.3"
